# TagGame Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/TagGame

#==================#
#   Basic Config   #
#==================#

#==================#
#   Games Config   #
#==================#
# Countdown time(sec) when starting the game
StartCountdownInSec: 10

#====================#
#   Logging Config   #
#====================#
# DetailLogDirectory
DetailDirectory: plugins/TagGame/detail/

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
DontTouchThisConfig: 0.1